### ISSUE TITLE
Program allows for Quads in input

### ISSUE THREAD

**Issue by cole21771** [dennis-classes/se2832-lab-01-isosceles-aureo96#4]
**Input:**
3 3 3 3
**Expected Result:**
The triangle 3 3 3 3 is not a valid triangle         **OR**
This shape 3 3 3 3 is not a valid triangle
**Actual Result:**
The triangle 3 3 3 3 is a valid triangle. The triangle is an equilateral triangle.

**Comment by aureo96** [comment]
I fixed this issue now. Please feel free to test the application more!
